import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToasterProvider from "@/providers/ToasterProvider";
import SideNavigation from "@/components/layout/SideNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vision Pro: Plant Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  context,
  children,
}: Readonly<{
  context: any;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider>
          <div className="bg-cover bg-no-repeat bg-[url('../assets/images/background.jpg')]">
            <div className="  container flex gap-10  justify-center items-center h-screen w-full ">
              <SideNavigation />
              <div className="  text-white max-h-[700px] h-full w-[700px]  shrink-0 flex-1    bg-white  rounded-2xl bg-opacity-40  backdrop-blur-lg">
                {children}
              </div>
            </div>
          </div>
        </ToasterProvider>
      </body>
    </html>
  );
}
